{{- if .Values.ExternalSecret.enabled }}
{{- range $key, $value := .Values.ExternalSecret.resources }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:  
  name: {{ $key }}
  annotations:
      {{ with $value.annotations }} 
      {{ . | toYaml | nindent 3 }}
      {{ end }}
spec:
{{ with $value.spec }} 
{{ . | toYaml | nindent 2 }}
{{ end }}
---
{{ end }}
{{ end }}


