{{- if .Values.hpa.enabled }}
{{- range $key, $value := .Values.hpa.resources }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $key }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $key }}
  minReplicas: {{ $value.minReplicas }}
  maxReplicas: {{ $value.maxReplicas }}
  metrics:
    {{- if $value.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $value.targetCPU }}
    {{- end }}
    {{- if $value.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $value.targetMemory }}
    {{- end }}
  behavior:
    {{ with $value.behavior }} 
    {{ . | toYaml | nindent 8 }}
    {{ end }}
---
{{- end }}
{{ end }}
