{{- if .Values.services }}
{{- range $value := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $value.name }}"
  namespace: {{ $.Release.Namespace }}
  labels:
{{ if $value.labels }}
    {{- with $value.labels -}}
    {{- .| toYaml | indent 4 -}}
    {{ end }}
{{ else }}
    {{- include "generic.labels" $ | nindent 4 }}
{{ end }}
  annotations:
    {{ with $value.annotations }}
    {{- .| toYaml | indent 4}}
    {{ end }}
spec:
  type: {{ $value.type }}
  ports:
    - name: {{ $value.portName }}
      port: {{ $value.containerPort }}
      {{ if $value.targetPort }}
      targetPort: {{ $value.targetPort }}
      {{ end }}    
      {{ if and (eq $value.type "NodePort") ($value.nodePort)}}
      nodePort: {{ $value.nodePort }}
      {{ end }}
      protocol: {{ $value.protocol }}
  selector: 
    {{- range $value := $value.selectorLabels }}
    {{ end }}  
---
{{- end }}
{{- end }}
